language: go
os:
    - linux
    - osx
install:
    - go get -t -d -v ./...
script:
    - go build ./cmd/notes && ./notes --help
    - go test -v -race -coverprofile=coverage.txt
after_success:
  - bash <(curl -s https://codecov.io/bash)
